[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 128

[profile.ci.fuzz]
runs = 10000

[profile.ci.invariant]
runs = 512
depth = 256

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
sort_imports = true
